---
- hosts: webservers
  remote_user: dcg
  become: true
  become_method: sudo
  tasks:
    - name: Remove php
      apt:
        name: php
        state: absent
        update_cache: no
        purge: yes
        autoremove: yes
